services:
  vault:
    hostname: vault
    container_name: vault
    image: registry.namachain.com/namachain/vault:${vault_IMAGE_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - APP_VAULT__KEY=${APP_VAULT__KEY}
    depends_on:
      userchain:
        condition: service_healthy
    networks:
      localnet:
        aliases:
          - vault
    ports:
      - "2000:80"
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 5s
      timeout: 10s
      retries: 0
      start_period: 5s
  credsdeploy:
    image: registry.namachain.com/namachain/webcaller:${credsdeploy_IMAGE_TAG}
    entrypoint: [ "curl", "--location", "--request", "POST", "http://vault:80/api/service/deploy", "--header", "Content-Type: application/json", "--data-raw" ]
    networks:
      - localnet
  userchain:
    hostname: chain
    container_name: chain
    image: registry.namachain.com/namachain/chain:${userchain_IMAGE_TAG}
    ports:
      - "8888:8888"
    networks:
      localnet:
        aliases:
          - chain
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "http://localhost:8888/v1/chain/get_info"]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 10s
    volumes:
      - userchainconfig:/config
  userchaininit:
    hostname: chaininit
    container_name: chaininit
    image: registry.namachain.com/namachain/initializer.userchain:${userchaininit_IMAGE_TAG}
    networks:
      localnet:
        aliases:
          - chaininit
    volumes:
      - userchainconfig:/namachain
  authenticator:
    hostname: auth
    container_name: auth
    image: registry.namachain.com/namachain/authenticator:${authenticator_IMAGE_TAG}
    ports: 
      - "5000:80"
    depends_on: 
      userchain:
        condition: service_healthy
      vault:
        condition: service_healthy
    networks:
      localnet:
        aliases:
          - auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 0
      start_period: 10s
  authcredentials:
    extends:
      service: credsdeploy
    container_name: authcreds
    depends_on:
      authenticator:
        condition: service_healthy
      vault:
        condition: service_started
    command: [ "{\"baseUrl\":\"http://auth:80\",\"account\": \"nama.auth\"}" ]
  app:
    hostname: app
    container_name: app
    image: registry.namachain.com/namachain/app:${app_IMAGE_TAG}
    ports: 
      - "81:80"
    depends_on:
      userchain:
        condition: service_healthy
      authenticator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 5s
      timeout: 10s
      retries: 0
      start_period: 8s
    networks:
      localnet:
        aliases:
          - app
      redisnet:
        aliases:
          - app
      mailnet:
        aliases:
          - app
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
  appcredentials:
    extends:
      service: credsdeploy
    container_name: appcreds
    depends_on:
      app:
        condition: service_healthy
      vault:
        condition: service_started
    command: [ "{\"baseUrl\":\"http://app:80\",\"account\": \"nama.account\"}" ]
  business:
    hostname: business
    container_name: business
    image: registry.namachain.com/namachain/business:${business_IMAGE_TAG}
    ports:
      - "83:80"
    depends_on:
      userchain:
        condition: service_healthy
      authenticator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 5s
      timeout: 10s
      retries: 0
      start_period: 8s
    networks:
      localnet:
        aliases:
          - business
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
  businesscredentials:
    extends:
      service: credsdeploy
    container_name: businesscreds
    depends_on:
      business:
        condition: service_healthy
      vault:
        condition: service_started
    command: [ "{\"baseUrl\":\"http://business:80\",\"account\": \"nama.account\"}" ]
  portal:
    hostname: portal
    container_name: portal
    image: registry.namachain.com/namachain/portal:${portal_IMAGE_TAG}
    ports: 
      - "82:80"
    depends_on:
      userchain:
        condition: service_healthy
      authenticator:
        condition: service_healthy
      app:
        condition: service_healthy
    networks:
      localnet:
        aliases:
          - portal
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 5s
      timeout: 10s
      retries: 0
      start_period: 8s
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
  portalcredentials:
    extends:
      service: credsdeploy
    container_name: portalcreds
    depends_on:
      portal:
        condition: service_healthy
      vault:
        condition: service_started
    command: [ "{\"baseUrl\":\"http://portal:80\",\"account\": \"nama.portal\"}" ]
  mailserver:
    hostname: mail
    container_name: mail
    image: namshi/smtp
    restart: unless-stopped
    environment: 
      - GMAIL_USER=${EMAIL_USER}
      - GMAIL_PASSWORD=${EMAIL_PASS}
      - KEY_PATH=/sslv/namachain.com.key
      - CERTIFICATE_PATH=/sslv/namachain.com.crt
    networks:
      mailnet:
        aliases:
          - mail
    volumes:
      - sslv:/sslv
  redis:
    hostname: redis
    container_name: redis
    image: redis
    networks:
      redisnet:
        aliases:
          - redis
  kyc:
    hostname: kyc
    container_name: kyc
    image: registry.namachain.com/namachain/kyc:${kyc_IMAGE_TAG}
    ports:
      - "5004:80"
    depends_on:
      userchain:
        condition: service_healthy
      authenticator:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      localnet:
        aliases:
          - kyc
      redisnet:
        aliases:
          - kyc
      mailnet:
        aliases:
          - kyc
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - APP_ShuftiPro__Secret=${APP_ShuftiPro__Secret}
    healthcheck:
      test: [ "CMD", "curl", "-X", "GET", "http://localhost:80/api/v1/publickey" ]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 15s
  kyccredentials:
    extends:
      service: credsdeploy
    container_name: kyccreds
    depends_on:
      kyc:
        condition: service_healthy
      authcredentials:
        condition: service_completed_successfully
    command: [ "{\"baseUrl\":\"http://kyc:80\",\"account\":\"nama.kyc\"}" ]
  aml:
    hostname: aml
    container_name: aml
    image: registry.namachain.com/namachain/aml:${aml_IMAGE_TAG}
    ports:
      - "5010:80"
    depends_on:
      userchain:
        condition: service_healthy
      authenticator:
        condition: service_healthy
    networks:
      localnet:
        aliases:
          - aml
      mailnet:
        aliases:
          - aml
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - APP_ShuftiPro__Secret=${APP_ShuftiPro__Secret}
    healthcheck:
      test: [ "CMD", "curl", "-X", "GET", "http://localhost:80/api/v1/publickey" ]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 15s
  amlcredentials:
    extends:
      service: credsdeploy
    container_name: amlcreds
    depends_on:
      aml:
        condition: service_healthy
      vault:
        condition: service_started
    command: [ "{\"baseUrl\":\"http://aml:80\",\"account\":\"nama.aml\"}" ]
  serviceapi:
    hostname: serviceapi
    container_name: serviceapi
    image: registry.namachain.com/namachain/serviceapi:${serviceapi_IMAGE_TAG}
    ports:
      - "5020:80"
    depends_on:
      userchain:
        condition: service_healthy
      authenticator:
        condition: service_healthy
      redis:
        condition: service_started
      ybserver:
        condition: service_started
    networks:
      localnet:
        aliases:
          - serviceapi
      redisnet:
        aliases:
          - serviceapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    healthcheck:
      test: [ "CMD", "curl", "-X", "GET", "http://localhost:80/api/v1/publickey" ]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 15s
  serviceapicredentials:
    extends:
      service: credsdeploy
    container_name: serviceapicreds
    depends_on:
      serviceapi:
        condition: service_healthy
      vault:
        condition: service_started
    command: [ "{\"baseUrl\":\"http://serviceapi:80\",\"account\":\"nama.serv\"}" ]
  demoservice:
    hostname: demoservice
    container_name: demoservice
    image: registry.namachain.com/namachain/demoservice:${demoservice_IMAGE_TAG}
    ports:
      - "90:80"
    networks:
      localnet:
        aliases:
          - demoservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
  # PRODUCERS
  producer:
    image: registry.namachain.com/namachain/chain:${producer_IMAGE_TAG}
    healthcheck:
      test: [ "CMD", "curl", "-X", "POST", "http://localhost:8888/v1/chain/get_info" ]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 10s
  producerconfig:
    image: registry.namachain.com/namachain/producer:${producerconfig_IMAGE_TAG}
  producer1:
    extends:
      service: producer
    hostname: producer1
    container_name: producer1
    ports:
      - "8889:8888"
      - "9875:9876"
    networks:
      localnet:
        aliases:
          - producer1
    volumes:
      - producer1volume:/config
  producer1config:
    extends:
      service: producerconfig
    hostname: producer1config
    container_name: producer1config
    networks:
      - localnet
    volumes:
      - userchainconfig:/genesis
      - producer1volume:/namachain
    secrets:
      - source: prod1
        target: /config/producer.json
    depends_on:
      userchain:
        condition: service_healthy
      authenticator:
        condition: service_healthy
      app:
        condition: service_healthy
  ybmaster:
    image: yugabytedb/yugabyte:latest
    container_name: yb-master-n1
    volumes:
      - yb-master-data-1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-master-n1:7100",
               "--rpc_bind_addresses=yb-master-n1:7100",
               "--replication_factor=1"]
    ports:
      - "7000:7000"
    environment:
      SERVICE_7000_NAME: yb-master
    networks:
      localnet:
        aliases:
          - ybmaster

  ybserver:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-n1
    volumes:
      - yb-tserver-data-1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/tserver",
               "--start_pgsql_proxy",
               "--ysql_enable_auth",
               "--use_cassandra_authentication",
               "--rpc_bind_addresses=yb-tserver-n1:9100",
               "--tserver_master_addrs=yb-master-n1:7100"]
    ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    depends_on:
      - ybmaster
    networks:
      localnet:
        aliases:
          - ybserver
networks:
  localnet: {}
  mailnet: {}
  redisnet: {}
volumes:
  sslv:
    external: true
  userchainconfig:
    external: false
  producer1volume:
    external: false
  yb-master-data-1:
  yb-tserver-data-1:
secrets:
  prod1:
    file: ~/producer2/producer.json
  
