name: Build docker image

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'the Dockerfile to be built'
        required: true
        default: 'ActionsDockerfile'
      image_name:
        description: 'the name of the image'
        required: true
        default: 'actions'
      image_version:
        description: 'the image version'
        required: true
        default: '1.0.0'
  
jobs:
  build-and-deploy-to-staging:
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Login to docker
      run: echo ${{ secrets.DOCKERPASS }} | docker login registry.namachain.com -u ${{ secrets.DOCKERUSER }} --password-stdin

    - name: Build
      run: docker build . --file dockerfiles/${{ github.event.inputs.dockerfile }} --tag registry.namachain.com/namachain/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_version }} --tag registry.namachain.com/namachain/${{ github.event.inputs.image_name }}:latest

    - name: Publish
      run: docker push registry.namachain.com/namachain/${{ github.event.inputs.image_name }} --all-tags

    - name: Logout docker
      if: always()
      run: docker logout registry.namachain.com
