name: Get latest tag in branch

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      image_tag:
        description: "The docker image tag to be deployed"
        value: "${{ jobs.gettag.outputs.image_tag }}"

jobs:
  gettag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate_output.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
    - name: Generate-Output
      id: generate_output
      run: |
        tag=`git describe --tags | sed -E 's/(([0-9]+\.){2}[0-9]+-build[0-9]+).*/\1/g'`
        if [[ ! "$tag" == *build* ]]; then
          tag=`echo $tag | sed -E 's/(([0-9]+\.){2}[0-9]+).*/\1/g'`
        fi
        echo "::set-output name=image_tag::$tag"
