name: Publish Build

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      branch:
        required: true
        type: string
      csproj_dir:
        required: false
        type: string
        default: '.'
    secrets:
      GH_TOKEN:
        required: true
      PAT:
        required: true

jobs:
  publishbuild:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate_output.outputs.version }}
      build: ${{ steps.generate_output.outputs.build }}
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Namachain/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PAT }}

    - id: versionstep
      name: Extract version
      run: echo "version=$(grep '<Version>' < *.csproj | sed 's/.*<Version>\(.*\)<\/Version>/\1/' | cut -d '$' -f 1)" >> $GITHUB_ENV

    - run: echo "build=$(date +%s%N)" >> $GITHUB_ENV

    - name: Verify csproj
      run: cat *.csproj

    - name: Package
      run: dotnet pack --force --version-suffix -build${{ env.build }} -c Release

    - name: Publish
      run: dotnet nuget push -k $NUGET_AUTH_TOKEN -s https://nuget.pkg.github.com/Namachain/index.json ./bin/Release/*.nupkg

    - name: Tag with build version
      run: git tag ${{ env.version }}-build${{ env.build }}

    - run: git push origin --tags
